name: CD

on:
  workflow_run:
    workflows: ["CI"]  # CI 워크플로 이름
    types:
      - completed  # CI 완료 후 실행

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Create application.yml
        run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./application-deploy.yml
          echo "${{ secrets.DATA }}" > ./data.sql
          cat ./application-deploy.yml

      - name: Build project
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash

      - name: Enable Docker build
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

      - name: Build and push Docker image
        run: |
          docker build --platform linux/amd64 -t sfaas/server .
          docker push sfaas/server

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RELEASE_SERVER_IP }}
          username: ${{ secrets.RELEASE_SERVER_USER }}
          key: ${{ secrets.RELEASE_SERVER_KEY }}
          script: |
            cd ~
            ./deploy.sh